package lab.xelnagaPackage;


/**
* lab/xelnagaPackage/armyOfDronesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecieñ 2012 02:57:52 CEST
*/


// = observer
public final class armyOfDronesHolder implements org.omg.CORBA.portable.Streamable
{
  public lab.Drone value[] = null;

  public armyOfDronesHolder ()
  {
  }

  public armyOfDronesHolder (lab.Drone[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lab.xelnagaPackage.armyOfDronesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lab.xelnagaPackage.armyOfDronesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lab.xelnagaPackage.armyOfDronesHelper.type ();
  }

}
