package lab.xelnagaPackage;


/**
* lab/xelnagaPackage/armyOfDronesHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecieñ 2012 02:57:52 CEST
*/


// = observer
abstract public class armyOfDronesHelper
{
  private static String  _id = "IDL:lab/xelnaga/armyOfDrones:1.0";

  public static void insert (org.omg.CORBA.Any a, lab.Drone[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static lab.Drone[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = lab.DroneHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (lab.xelnagaPackage.armyOfDronesHelper.id (), "armyOfDrones", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static lab.Drone[] read (org.omg.CORBA.portable.InputStream istream)
  {
    lab.Drone value[] = null;
    int _len0 = istream.read_long ();
    value = new lab.Drone[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = lab.DroneHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, lab.Drone[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      lab.DroneHelper.write (ostream, value[_i0]);
  }

}
