######################################################################
# Automatically generated by qmake (2.01a) wt. cze 14 18:59:31 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += polygon.h renderarea.h
SOURCES += main.cpp polygon.cpp renderarea.cpp
