package lab;


/**
* lab/Air.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecieñ 2012 02:57:52 CEST
*/

public interface Air extends AirOperations, lab.Drone, org.omg.CORBA.portable.IDLEntity 
{
} // interface Air
