package lab;

/**
* lab/AirHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecień 2012 14:51:11 CEST
*/

public final class AirHolder implements org.omg.CORBA.portable.Streamable
{
  public lab.Air value = null;

  public AirHolder ()
  {
  }

  public AirHolder (lab.Air initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lab.AirHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lab.AirHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lab.AirHelper.type ();
  }

}
