package lab;


/**
* lab/AirOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecień 2012 14:51:11 CEST
*/

public interface AirOperations  extends lab.DroneOperations
{
  void justFly (int ticket);
} // interface AirOperations
