package lab;


/**
* lab/AirOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecieñ 2012 02:57:52 CEST
*/

public interface AirOperations  extends lab.DroneOperations
{
  void justFly ();
} // interface AirOperations
