package lab;


/**
* lab/DroneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecieñ 2012 02:57:52 CEST
*/

public interface DroneOperations 
{

  // = device
  String name ();

  // = device
  void name (String newName);
  int id ();
  void id (int newId);
  void command (String cmd);
  void add_overmind (lab.Overlord lstnr);
  void rem_overmind (lab.Overlord lstnr);
} // interface DroneOperations
