package lab;


/**
* lab/DroneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecień 2012 14:51:11 CEST
*/

public interface DroneOperations 
{

  // = device
  String name ();

  // = device
  void name (String newName);
  int id ();
  void id (int newId);
  void command (int ticket, String cmd);
  int getTicket ();
  void relTicket ();
  void add_overmind (lab.Overlord lstnr);
  void rem_overmind (lab.Overlord lstnr);
} // interface DroneOperations
