package lab;

/**
* lab/GroundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecień 2012 14:51:11 CEST
*/

public final class GroundHolder implements org.omg.CORBA.portable.Streamable
{
  public lab.Ground value = null;

  public GroundHolder ()
  {
  }

  public GroundHolder (lab.Ground initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lab.GroundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lab.GroundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lab.GroundHelper.type ();
  }

}
