package lab;


/**
* lab/Mutalisk.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecieñ 2012 02:57:52 CEST
*/

public interface Mutalisk extends MutaliskOperations, lab.Air, org.omg.CORBA.portable.IDLEntity 
{
} // interface Mutalisk
