package lab;

/**
* lab/OverlordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecieñ 2012 02:57:52 CEST
*/

public final class OverlordHolder implements org.omg.CORBA.portable.Streamable
{
  public lab.Overlord value = null;

  public OverlordHolder ()
  {
  }

  public OverlordHolder (lab.Overlord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lab.OverlordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lab.OverlordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lab.OverlordHelper.type ();
  }

}
