package lab;


/**
* lab/OverlordPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecieñ 2012 02:57:52 CEST
*/

@SuppressWarnings("unchecked")
public abstract class OverlordPOA extends org.omg.PortableServer.Servant
 implements lab.OverlordOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  @SuppressWarnings("rawtypes")
private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("detector", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // = listener
       case 0:  // lab/Overlord/detector
       {
         String event = in.read_string ();
         this.detector (event);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:lab/Overlord:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Overlord _this() 
  {
    return OverlordHelper.narrow(
    super._this_object());
  }

  public Overlord _this(org.omg.CORBA.ORB orb) 
  {
    return OverlordHelper.narrow(
    super._this_object(orb));
  }


} // class OverlordPOA
