package lab;

/**
* lab/XelnagaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecień 2012 14:51:11 CEST
*/

public final class XelnagaHolder implements org.omg.CORBA.portable.Streamable
{
  public lab.Xelnaga value = null;

  public XelnagaHolder ()
  {
  }

  public XelnagaHolder (lab.Xelnaga initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lab.XelnagaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lab.XelnagaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lab.XelnagaHelper.type ();
  }

}
