package lab;


/**
* lab/XelnagaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecień 2012 14:51:11 CEST
*/

public interface XelnagaOperations 
{

  // stupid CORBA, Y U can't put this inline?
  int xid ();

  // stupid CORBA, Y U can't put this inline?
  void xid (int newXid);
  lab.Drone searchDroneByName (String name);
  lab.Drone[] searchSpaceAndDestroyProtossRace ();
  void observeDrone (int id, lab.Overlord lstnr);
  void unobserveDrone (int id, lab.Overlord lstnr);
} // interface XelnagaOperations
