package lab;

/**
* lab/ZerglingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecieñ 2012 02:57:52 CEST
*/

public final class ZerglingHolder implements org.omg.CORBA.portable.Streamable
{
  public lab.Zergling value = null;

  public ZerglingHolder ()
  {
  }

  public ZerglingHolder (lab.Zergling initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = lab.ZerglingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    lab.ZerglingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return lab.ZerglingHelper.type ();
  }

}
