package lab;


/**
* lab/ZerglingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecień 2012 14:51:11 CEST
*/

public interface ZerglingOperations  extends lab.GroundOperations
{
  void cutEtherCables (int ticket);
} // interface ZerglingOperations
