package lab;


/**
* lab/ZerglingPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from root.idl
* wtorek, 24 kwiecień 2012 14:51:11 CEST
*/

public abstract class ZerglingPOA extends org.omg.PortableServer.Servant
 implements lab.ZerglingOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("cutEtherCables", new java.lang.Integer (0));
    _methods.put ("eatStudent", new java.lang.Integer (1));
    _methods.put ("_get_name", new java.lang.Integer (2));
    _methods.put ("_set_name", new java.lang.Integer (3));
    _methods.put ("_get_id", new java.lang.Integer (4));
    _methods.put ("_set_id", new java.lang.Integer (5));
    _methods.put ("command", new java.lang.Integer (6));
    _methods.put ("getTicket", new java.lang.Integer (7));
    _methods.put ("relTicket", new java.lang.Integer (8));
    _methods.put ("add_overmind", new java.lang.Integer (9));
    _methods.put ("rem_overmind", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // lab/Zergling/cutEtherCables
       {
         int ticket = in.read_long ();
         this.cutEtherCables (ticket);
         out = $rh.createReply();
         break;
       }

       case 1:  // lab/Ground/eatStudent
       {
         int ticket = in.read_long ();
         this.eatStudent (ticket);
         out = $rh.createReply();
         break;
       }


  // = device
       case 2:  // lab/Drone/_get_name
       {
         String $result = null;
         $result = this.name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // = device
       case 3:  // lab/Drone/_set_name
       {
         String newName = in.read_string ();
         this.name (newName);
         out = $rh.createReply();
         break;
       }

       case 4:  // lab/Drone/_get_id
       {
         int $result = (int)0;
         $result = this.id ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // lab/Drone/_set_id
       {
         int newId = in.read_long ();
         this.id (newId);
         out = $rh.createReply();
         break;
       }

       case 6:  // lab/Drone/command
       {
         int ticket = in.read_long ();
         String cmd = in.read_string ();
         this.command (ticket, cmd);
         out = $rh.createReply();
         break;
       }

       case 7:  // lab/Drone/getTicket
       {
         int $result = (int)0;
         $result = this.getTicket ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // lab/Drone/relTicket
       {
         this.relTicket ();
         out = $rh.createReply();
         break;
       }

       case 9:  // lab/Drone/add_overmind
       {
         lab.Overlord lstnr = lab.OverlordHelper.read (in);
         this.add_overmind (lstnr);
         out = $rh.createReply();
         break;
       }

       case 10:  // lab/Drone/rem_overmind
       {
         lab.Overlord lstnr = lab.OverlordHelper.read (in);
         this.rem_overmind (lstnr);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:lab/Zergling:1.0", 
    "IDL:lab/Ground:1.0", 
    "IDL:lab/Drone:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Zergling _this() 
  {
    return ZerglingHelper.narrow(
    super._this_object());
  }

  public Zergling _this(org.omg.CORBA.ORB orb) 
  {
    return ZerglingHelper.narrow(
    super._this_object(orb));
  }


} // class ZerglingPOA
