######################################################################
# Automatically generated by qmake (2.01a) sob. cze 18 21:28:08 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PlotArea.h RealLife.h
SOURCES += main.cpp PlotArea.cpp RealLife.cpp
