######################################################################
# Automatically generated by qmake (2.01a) sob. cze 18 19:51:18 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
