######################################################################
# Automatically generated by qmake (2.01a) sob. cze 18 20:04:33 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PlotArea.h
SOURCES += main.cpp PlotArea.cpp
