module lab {
	interface Overlord { // = listener
		void detector(in string event);
	};
	interface Drone { // = device
		attribute string name;
		attribute long id;
		void command(in long ticket, in string cmd);
		long getTicket();
		void relTicket(); 
		void add_overmind(in Overlord lstnr);
		void rem_overmind(in Overlord lstnr);
	};
	
	interface Ground : Drone {
		void eatStudent(in long ticket);
	};
	
	interface Zergling : Ground {
		void cutEtherCables(in long ticket);
	};
	
	interface Air : Drone {
		void justFly(in long ticket);
	};
	
	interface Mutalisk : Air {
		void disableWPA(in long ticket);
	};
	
	
	
	interface Xelnaga { // = observer / factory
		typedef sequence<Drone> armyOfDrones; // stupid CORBA, Y U can't put this inline?
	
		attribute long xid;
		Drone searchDroneByName(in string name);
		armyOfDrones searchSpaceAndDestroyProtossRace();
		void observeDrone(in long id, in Overlord lstnr);
		void unobserveDrone(in long id, in Overlord lstnr);
		//void controlDrone(in long id);
		//void abandonDrone(in long id);
	};
};